# Generated by Django 6.0.4 on 2026-05-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('year', models.IntegerField()),
                ('unit', models.CharField(choices=[('comedy', 'Comedy'), ('action', 'Action'), ('crime', 'Crime'), ('horror', 'Horror')], max_length=20)),
            ],
        ),
    ]
