# Generated by Django 6.0.4 on 2026-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
